# Root Terragrunt configuration
# This file contains shared configuration that can be inherited by all environments and layers

# Common configuration (naming conventions, tags, etc.)
# Merged from common.hcl to avoid nested includes
locals {
  # Extract path components for naming
  # Path format: live/{env}/{region}/{layer}/{resource}
  path_parts = split("/", get_terragrunt_dir())
  path_len = length(local.path_parts)
  
  # Get environment from path (live/{env}/...) - index 1 from start
  environment = try(
    element(local.path_parts, 1),
    get_env("ENVIRONMENT", "dev")
  )
  
  # Get region from path (live/{env}/{region}/...) - index 2 from start
  region = try(
    element(local.path_parts, 2),
    get_env("AWS_REGION", "us-east-1")
  )
  
  # Get layer from path (live/{env}/{region}/{layer}/...) - index 3 from start
  layer = try(
    element(local.path_parts, 3),
    "unknown"
  )
  
  # Get resource name from path (live/{env}/{region}/{layer}/{resource}) - index 4 from start
  resource_name = try(
    element(local.path_parts, 4),
    "default"
  )
  
  # Project name
  project_name = "acme-platform"
  
  # Region shortening - convert full region names to short codes
  region_short = replace(
    replace(
      replace(
        replace(local.region, "ap-southeast-1", "apse1"),
        "us-east-1", "useast1"
      ),
      "us-west-2", "uswest2"
    ),
    "eu-west-1", "euwest1"
  )
  
  # Standard resource name
  resource_name_standard = "${local.project_name}-${local.environment}-${local.region_short}-${local.resource_name}"
  
  # Short resource name
  short_name = "${local.environment}-${local.region_short}-${local.resource_name}"
  
  # Common tags applied to all resources
  common_tags_base = {
    Project     = local.project_name
    Environment = local.environment
    Region      = local.region
    Layer       = local.layer
    ManagedBy   = "Terraform"
    Repository  = "terragrunt-layers"
  }
  
  # Environment-specific tags
  environment_tags_dev = {
    CostCenter = "development"
    Owner      = "platform-team"
  }
  
  environment_tags_staging = {
    CostCenter = "staging"
    Owner      = "platform-team"
  }
  
  environment_tags_prod = {
    CostCenter = "production"
    Owner      = "platform-team"
    Backup     = "required"
  }
  
  # Final tags based on environment
  common_tags = local.environment == "dev" ? merge(local.common_tags_base, local.environment_tags_dev) : (
    local.environment == "staging" ? merge(local.common_tags_base, local.environment_tags_staging) : 
    merge(local.common_tags_base, local.environment_tags_prod)
  )
}

# Configure Terragrunt to automatically store tfstate files in an S3 bucket
# Note: Layer 0 Foundation must be deployed first to create the S3 bucket and DynamoDB table
remote_state {
  backend = "s3"
  config = {
    bucket         = get_env("TF_STATE_BUCKET", "terraform-state-${get_env("ENVIRONMENT", "dev")}-${get_env("AWS_REGION", "us-east-1")}")
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = get_env("AWS_REGION", "us-east-1")
    encrypt        = true
    dynamodb_table = get_env("TF_LOCK_TABLE", "terraform-locks")
  }
}

# Note: Provider configuration is generated by child configs as needed
# This avoids conflicts with modules that already define required_providers
# Child configs should generate provider.tf if the module doesn't have it

# Inputs that can be overridden by child configurations
inputs = {
  # Naming conventions
  naming_convention = {
    resource_name        = local.resource_name_standard
    short_name          = local.short_name
    s3_bucket           = "${local.project_name}-${local.environment}-${local.region_short}-${local.resource_name}"
    dynamodb_table      = "${local.project_name}-${local.environment}-${local.region_short}-${local.resource_name}"
    kms_alias           = "alias/${local.project_name}/${local.environment}/${local.region_short}/${local.resource_name}"
    iam_role            = "${substr(local.project_name, 0, 8)}-${local.environment}-${substr(local.region_short, 0, 6)}-${substr(local.resource_name, 0, 10)}-role"
    security_group      = "${local.project_name}-${local.environment}-${local.region_short}-${local.resource_name}-sg"
    cloudwatch_log_group = "/aws/${local.project_name}/${local.environment}/${local.region_short}/${local.resource_name}"
    eks_cluster         = "${local.environment}-${local.region_short}-${local.resource_name}"
    vpc                 = "${local.project_name}-${local.environment}-${local.region_short}-vpc"
  }
  
  # Common tags (automatically includes environment-specific tags)
  common_tags = local.common_tags
  
  # Environment and region
  environment  = local.environment
  aws_region   = local.region
  layer        = local.layer
  project_name = local.project_name
}

